services:
  web-router-manager:
    build: .
    container_name: router_app
    ports:
      - "5000:5000"
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: cisco.commands
      KAFKA_GROUP_ID: cisco-router-worker
      ROUTER_IP: 192.168.164.130
      ROUTER_USERNAME: admin
      ROUTER_PASSWORD: cisco
    networks:
      - app-network

networks:
  app-network:
    external: true
